### ISSUE TITLE
Create production server; Setup SSL

### ISSUE THREAD

**Issue by allthesignals** [MAPC/cool-places#12]
- [x] Production server on Linux EC2 instance, with nginx config: http://vanderwijk.info/blog/hosting-ember-cli-app-nginx/
 - [x] Communication with IT on updating DNS
 - [x] SSL setup with letsencrypt - ensure this works with internal DNS

**Comment by allthesignals** [comment]
This is the config I'll need to provide to deploy to Linux box:
```
// ...
    'ssh-index': {
      remoteDir: "/usr/local/www/myapp",
      username: "www",
      host: "192.168.0.136",
      privateKeyFile: "/Users/me/.ssh/id_rsa",
      allowOverwrite: true
    },
    rsync: {
      dest: "/usr/local/www/myapp",
      username: "www",
      host: "192.168.0.136",
      delete: false
    }
// ...
```

**Comment by allthesignals** [comment]
We may also need to be careful about the cache-busting... the file expiration dates shouldn't be infinite. My deploy lib should handle this, but as an extra precaution.

**Comment by mzagaja** [comment]
@allthesignals What file does that config go into?

**Comment by allthesignals** [comment]
@mzagaja I have a commit on this branch https://github.com/MAPC/cool-places/commit/bd6fc5dab14bf1d2a352a6d5089505b3bacc0a19

**Comment by allthesignals** [comment]
https://github.com/MAPC/cool-places/tree/deploy-setup

**Comment by mzagaja** [comment]
@allthesignals ok thanks. Are you ok if I commit to the branch directly with the correct config and then we can test it?

**Comment by allthesignals** [comment]
@mzagaja sounds great!

**Comment by mzagaja** [comment]
This deploy script does not like encrypted private keys on OS X so I'm struggling with it, that being said my manual deploy appears to be working.

**Comment by mzagaja** [comment]
Closing because this is on production.
