### ISSUE TITLE
Take Site Offline

### ISSUE THREAD

**Issue by theryankelly** [MAPC/cool-places#17]
The site is not currently functioning and would require some development to address the issues.  We would like to consider trying to resurrecting this page next year, but need to take offline for this coming season.

- [ ] Develop short Qualtrics survey for feedback. Take questions from similar projects. 
- [ ] Replace site with error page.  XD mock up is located in K drive project folder as "Keep Cool Error Page".
![Screen Shot 2019-04-23 at 12 18 18 PM](https://user-images.githubusercontent.com/2421382/57553445-7e8e5580-733c-11e9-947b-626cb8f7a3ec.png)

**Comment by theryankelly** [comment]
Link to "Give Feedback" survey.  This should email/notify digital (at) mapc: https://mapc.az1.qualtrics.com/jfe/form/SV_3z87isx71JiBXjD

**Comment by allthesignals** [comment]
Happy to assist with the Ember side of things if needed!

...but summer is over at this point so maybe next time.

**Comment by allthesignals** [comment]
Awww. Bye bye app... and remember: keep cool. ;) ;) ;) ;) ;) 🙄
